Revert "chore: Move path join into platform-independent code"
zip-rs/zip2 pull request #125
Opened 2024-05-15 15:47 UTC by cosmicexplorer

This reverts commit f275acf1d279061074f089cb0049c8641b0495ff, as there appears to be no platform-independent way to create an `OsString` (see links in docstring for [`OsString::from_encoded_bytes_unchecked()`](https://doc.rust-lang.org/std/ffi/struct.OsString.html#method.from_encoded_bytes_unchecked)). This is causing a [failure](
https://github.com/zip-rs/zip2/actions/runs/9085755853/job/24969824813) on master.

While I tried to see how platform-dependent `OsString` parsing would work (see https://github.com/zip-rs/zip2/compare/master...cosmicexplorer:fix-path-join?expand=1), it ends up being a bit of a mess and I believe the original code is probably better.

Please let me know if I'm missing something here!

2024-05-15 15:51 UTC, cosmicexplorer commented
cc @Pr0methean as I can't add reviewers (that's fine, I'm not asking for more permissions).

2024-05-15 15:53 UTC, cosmicexplorer commented
Ok, now I've tried actually using the platform-specific code to extract an `OsString` since apparently windows was failing even before that. I think I actually should be reverting a prior commit instead of inserting my own code, so let me try that now.

2024-05-15 15:58 UTC, cosmicexplorer commented
Hmmm, I actually think the change I've added in aef0bb6 is necessary, as master appears to have been broken since https://github.com/zip-rs/zip2/commit/8715d936cbd3e0fdc2e778b70d8a02e2dfc16fc2. Please let me know if I'm mistaken -- I am extremely unfamiliar with handling windows paths and strings and I have no clue whether there's a more canonical approach that I'm missing.

2024-05-15 16:10 UTC, cosmicexplorer commented
I'm going to make another PR adding `cfg-if` as a dependency because the conditional compilation sections are now getting pretty hairy.

2024-05-15 16:14 UTC, cosmicexplorer commented
Just squashed and force pushed to clarify that no commits were reverted. Will update the description.

2024-05-15 21:28 UTC, Pr0methean requested changes

2024-05-15 21:28 UTC, Pr0methean commented on src/read.rs
> +                 * doesn't specify! */
```suggestion
                // Extract symlinks as symlinks
```
The bug was that symlinks were extracted as normal files.

2024-05-15 21:28 UTC, Pr0methean commented on src/read.rs
> +                        );
Aren't symlinks stored in UTF-8, given the general principle that file paths are Unix-style? The APPNOTE doesn't specifically address this.

2024-05-15 21:28 UTC, Pr0methean commented on src/read.rs
> +                            .map(|c| u16::from_le_bytes(c.try_into().unwrap()))
This will panic if a character code point is above 0xFFFF, because that has to be encoded in UTF-16 as a surrogate pair.

2024-05-15 21:36 UTC, Pr0methean commented
From the description of `The byte encoding is an unspecified, platform-specific, self-synchronizing superset of UTF-8. By being a self-synchronizing superset of UTF-8, this encoding is also a superset of 7-bit ASCII.`

Since UTF-16 isn't a superset of UTF-8, passing UTF-16 to it is wrong.

```
The byte encoding is an unspecified, platform-specific, self-synchronizing superset of UTF-8. By being a self-synchronizing superset of UTF-8, this encoding is also a superset of 7-bit ASCII.
```

2024-05-16 00:24 UTC, Pr0methean commented
Closing since https://github.com/zip-rs/zip2/actions/runs/9104341554/job/25028016801 shows that the issue is fixed.

2024-05-16 00:24 UTC, closed without merging